phrase = "Hello World"
print(phrase)
print("---^---")
print("---|---")
print("---|---")
print("---|---")
print("---|---")
print("---|---")
print("---|---")
print("-------")
print("Cam changed something!")